### PR TITLE
add flatpak installer justfile to home folder

### LINKED ISSUE #20: Install System Flatpaks
I think we need just/ujust first then:

```
flatpak remote-add --system flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -y \
app/io.github.dvlv.boxbuddyrs/x86_64/stable \
app/com.github.rafostar.Clapper/x86_64/stable \
app/org.fedoraproject.MediaWriter/x86_64/stable \
app/com.github.tchx84.Flatseal/x86_64/stable \
app/io.github.flattool.Warehouse/x86_64/stable \
app/org.gnome.baobab/x86_64/stable \
app/org.gnome.Calculator/x86_64/stable \
app/org.gnome.Calendar/x86_64/stable \
app/org.gnome.Characters/x86_64/stable \
app/org.gnome.clocks/x86_64/stable \
app/org.gnome.Connections/x86_64/stable \
app/org.gnome.Contacts/x86_64/stable \
app/org.gnome.DejaDup/x86_64/stable \
app/org.gnome.Papers/x86_64/stable \
app/com.mattjakeman.ExtensionManager/x86_64/stable \
app/org.gnome.FileRoller/x86_64/stable \
app/org.gnome.font-viewer/x86_64/stable \
app/org.gnome.Logs/x86_64/stable \
app/org.gnome.Loupe/x86_64/stable \
app/org.gnome.Maps/x86_64/stable \
app/org.gnome.NautilusPreviewer/x86_64/stable \
app/org.gnome.World.PikaBackup/x86_64/stable \
app/org.gnome.TextEditor/x86_64/stable \
app/org.gnome.Weather/x86_64/stable \
app/io.missioncenter.MissionCenter/x86_64/stable \
app/org.mozilla.firefox/x86_64/stable \
app/org.mozilla.Thunderbird/x86_64/stable \
runtime/org.gtk.Gtk3theme.adw-gtk3/x86_64/3.22 \
runtime/org.gtk.Gtk3theme.adw-gtk3-dark/x86_64/3.22 \

```

### PR DESCRIPTION
**Pull request by hanthor**

### CODE REVIEW

**Comment by tulilirockz** [comment]
Oh theres no need to do that! You can just copy the `install-system-flatpaks` recipe off of bluefin!

**Comment by tulilirockz** [comment]
```
install-system-flatpaks:
    #!/usr/bin/bash
    FLATPAKS="bluefin_flatpaks/flatpaks"
    FLATPAK_LIST="$(curl https://raw.githubusercontent.com/ublue-os/bluefin/main/${FLATPAKS} | tr '\n' ' ')"
    flatpak --system -y install --or-update ${FLATPAK_LIST}
```

**Review by hanthor — COMMENTED** [review]
just tested locally

**Review by tulilirockz — APPROVED** [review]
LGTM!

**Pull request merged**
