### PR TITLE
Fix just file and add brew-doctor command

### PR DESCRIPTION
**Pull request by hanthor**
Correct the just file location and Just brew-doctor command to ensure proper Homebrew setup.

### CODE REVIEW

**Comment by tulilirockz** [comment]
omg im sorry i wanted to remove the font changes this one but i accidentally made a commit that removes it

**Comment by hanthor** [comment]
Fixed take another look @tulilirockz

**Comment by tulilirockz** [comment]
This is not necessary if we do #34. This will also break whenever gcc does a major update :(

**Comment by castrojo** [comment]
Gotcha, merging the other one.

**Pull request closed without merging**
